##The website title
name: Toastrack Bus
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: pygments
##toastrack is a UK vehicle
timezone: Europe/London

##draft items
exclude: []

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://toastrackbus.org
sass:
  sass_dir: _sass
  style: :compressed

paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title/

##The website description (to be used in meta tags)
description: University of Southampton - Toastrack Bus
##Some frequently used keywords on your website
keywords: some, relevant, keywords, for, usage, in metatags

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
ga_id: UA-57191586-2
#ga_domain: analyticsDomain

##Some commonly used links
links:
  #facebook: username
  #twitter: username
  email: webmaster@toastrackbus.org
  github: toastrack

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: placeholder.jpg
##comment this if you want full width posts with no sidebar
#sidebar: on

encoding: UTF-8


collections:
    display-photos-lowres:
        output: true
    display-photos-mediumres:
        output: true
    technical-drawings-lowres:
        output: true
    technical-drawings-mediumres:
        output: true
    recent_events:
        output: true
